---
format:
  revealjs:
    incremental: false
    css: ../styles.css
execute: 
  echo: true
---

# １日目：AIとソフトのインストール

2024-04-02

## 生成AIが何をやっているのか？

- みなさん、生成AI（ChatGPT、DeepLなど）って使っていますか？

- 私も使っています

- でも、そもそもAIって何か、分かりますか？

## **A**rtificial **I**ntelligenceという名前は嘘

- 「機械認知」
  - この呼び方は非常にミスリードイング！

- AIは何も**考えて**いない！
  - 真偽を知らない！

## LLMは言葉を予測するモデルである

- いわゆる「生成AI」は**Large Language Model**（LLM）の一種である
  - **言葉を予測する**モデル
  - 莫大的な量のデータ（インターネットの大部分）を使っている

- LLMは入力された言葉に対して、最も確率の高い次に来る言葉を返す

## LLMは言葉を予測するモデルである

<!-- show example of token visualizer -->

## LLMは必ず「もっともらしい」言葉を自信満々で返す

・・けど、それが正解とは**限らない**

- 平気な顔で**嘘をつく**

- LLMが返した言葉を信用できるかどうか判断するのが**あなたの責任**

## じゃ、どうやって使ったら良いのか？（DO）

- 返ってきた答えを**確かめる**
  - コードを走らせてみる
  - 内容を他のソースで確認する
  - 裏付けとなっている文献を出すように指示する

- 必ず批判的なスタンスを持つこと

## コピペしないこと（DO NOT）

- 大学とは自分で考えることを身につける場である
- 「言葉の計算機」だと思えば良い
  - 計算機があるからといって、算数を全く勉強しなくていいわけではない
- LLMは色々な作業を手伝う（よく嘘をつく）アシスタントであるが、自分の代わりに考えるものではない！

## 宿題

- 自分が得意（詳しい）分野についてChatGPTに質問して、しばらく会話をしてください
  - 嘘を見つけたら、それをメモってください

- 例